server {
    listen 80;
    server_name localhost;

    # Giao diện Frontend tĩnh
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Định tuyến Proxy ngược (Reverse Proxy) sang Backend API
    location /api/ {
        # backend là tên service được phân giải động bởi DNS nội bộ của Docker Bridge
        proxy_pass http://backend:5000/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
